In [5]:
import time
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.chrome.service import Service
import random

# Installing Modules

In [6]:
#!pip install selenium
#!pip install webdriver_manager
#!pip install pandas 
#!pip install numpy

# Scraping the data and links of all the states
1. Target website =  http://www.city-data.com
2. Target class: cities_list

In [22]:
options = Options()
#driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),options=options) 
driver = webdriver.Chrome()
driver.maximize_window()
url = 'http://www.city-data.com'
driver.get(url)
time.sleep(5)
states = driver.find_elements(By.CLASS_NAME,'cities_list')

state_links = []
state_names = []
for i in states:
    state_links.append(i.get_attribute('href'))
    state_names.append(i.text)
    
driver.close()

In [23]:
state_links = state_links[52:]
state_names = state_names[52:]

for i in range (0,52):
    print(state_names[i]," : ",state_links[i])

Alabama  :  http://www.city-data.com/city/Alabama.html
Alaska  :  http://www.city-data.com/city/Alaska.html
Arkansas  :  http://www.city-data.com/city/Arkansas.html
Arizona  :  http://www.city-data.com/city/Arizona.html
California  :  http://www.city-data.com/city/California.html
Colorado  :  http://www.city-data.com/city/Colorado.html
Connecticut  :  http://www.city-data.com/city/Connecticut.html
Delaware  :  http://www.city-data.com/city/Delaware.html
District of Columbia  :  http://www.city-data.com/city/District-of-Columbia.html
Florida  :  http://www.city-data.com/city/Florida.html
Georgia  :  http://www.city-data.com/city/Georgia.html
Hawaii  :  http://www.city-data.com/city/Hawaii.html
Idaho  :  http://www.city-data.com/city/Idaho.html
Illinois  :  http://www.city-data.com/city/Illinois.html
Indiana  :  http://www.city-data.com/city/Indiana.html
Iowa  :  http://www.city-data.com/city/Iowa.html
Kansas  :  http://www.city-data.com/city/Kansas.html
Kentucky  :  http://www.city-data.com/city/Kentucky.html
Louisiana  :  http://www.city-data.com/city/Louisiana.html
Maine  :  http://www.city-data.com/city/Maine.html
Maryland  :  http://www.city-data.com/city/Maryland.html
Massachusetts  :  http://www.city-data.com/city/Massachusetts.html
Michigan  :  http://www.city-data.com/city/Michigan.html
Minnesota  :  http://www.city-data.com/city/Minnesota.html
Mississippi  :  http://www.city-data.com/city/Mississippi.html
Missouri  :  http://www.city-data.com/city/Missouri.html
Montana  :  http://www.city-data.com/city/Montana.html
Nebraska  :  http://www.city-data.com/city/Nebraska.html
Nevada  :  http://www.city-data.com/city/Nevada.html
New Hampshire  :  http://www.city-data.com/city/New-Hampshire.html
New Jersey  :  http://www.city-data.com/city/New-Jersey.html
New Mexico  :  http://www.city-data.com/city/New-Mexico.html
New York  :  http://www.city-data.com/city/New-York.html
North Carolina  :  http://www.city-data.com/city/North-Carolina.html
North Dakota  :  http://www.city-data.com/city/North-Dakota.html
Ohio  :  http://www.city-data.com/city/Ohio.html
Oklahoma  :  http://www.city-data.com/city/Oklahoma.html
Oregon  :  http://www.city-data.com/city/Oregon.html
Pennsylvania  :  http://www.city-data.com/city/Pennsylvania.html
Rhode Island  :  http://www.city-data.com/city/Rhode-Island.html
South Carolina  :  http://www.city-data.com/city/South-Carolina.html
South Dakota  :  http://www.city-data.com/city/South-Dakota.html
Tennessee  :  http://www.city-data.com/city/Tennessee.html
Texas  :  http://www.city-data.com/city/Texas.html
Utah  :  http://www.city-data.com/city/Utah.html
Vermont  :  http://www.city-data.com/city/Vermont.html
Virginia  :  http://www.city-data.com/city/Virginia.html
Washington  :  http://www.city-data.com/city/Washington.html
West Virginia  :  http://www.city-data.com/city/West-Virginia.html
Wisconsin  :  http://www.city-data.com/city/Wisconsin.html
Wyoming  :  http://www.city-data.com/city/Wyoming.html
Small towns  :  http://www.city-data.com/smallTowns.html

# Data sets
Data sets should containg the following information about all of the states. 
1. Capital 
2. 2019 population 
3. Change from 2000 
4. Births 2000-2019
5. Deaths 2000-2019
6. Internal migration 2000-2019
7. International migration 2000-2019
8. 2019 housing units
9. Housing units change from 2000
10. Land area
11. State nickname

In [56]:
stateName, DS1_a0 ,DS1_a1 ,DS1_a2,DS1_a3,DS1_a4,DS1_a5,DS1_a6,DS1_a7,DS1_a8,DS1_a9,DS1_a10 = [],[],[],[],[],[],[],[],[],[],[], []

In [57]:
options = Options()
#driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),options=options) 
driver = webdriver.Chrome()
driver.maximize_window()

leftover_index = []
leftover_link =[]
for state in range (0, len(state_links)):
    try:
        driver.get(state_links[state])
    
        #Getting the values of the 11 fields
        list_group = driver.find_element(By.CLASS_NAME,'list-group')
        values = list_group.find_elements(By.CLASS_NAME,'badge')
    
        if(len(values) == 11):
            DS1_a0.append(values[0].text)
            DS1_a1.append(values[1].text)
            DS1_a2.append(values[2].text)
            DS1_a3.append(values[3].text)
            DS1_a4.append(values[4].text)
            DS1_a5.append(values[5].text)
            DS1_a6.append(values[6].text)
            DS1_a7.append(values[7].text)
            DS1_a8.append(values[8].text)
            DS1_a9.append(values[9].text)
            DS1_a10.append(values[10].text)
            stateName.append(state_names[state])
        
        else:
            leftover_link.append(state_links[state])
            leftover_index.append(state)
            print("We have a value exception at state link index ",state)
    
    except:
        print("State information not available at state link index ",state)
        continue
        
driver.quit()

We have a value exception at state link index  8
State information not available at state link index  51

In [58]:
data = {
    "State":stateName,
    "Capital":DS1_a0,
    "2019 population":DS1_a1,
    "Change from 2000":DS1_a2,
    "Births 2000-2019":DS1_a3,
    "Deaths 2000-2019":DS1_a4,
    "Internal migration 2000-2019":DS1_a5,
    "International migration 2000-2019":DS1_a6,
    "2019 housing units":DS1_a7,
    "Housing units change from 2000":DS1_a8,
    "Land area":DS1_a9,
    "State nickname":DS1_a10,
}

# Create the DataFrame
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

             State         Capital 2019 population Change from 2000  \
0          Alabama      Montgomery       4,841,799         +394,699
1           Alaska          Juneau         736,283         +109,351
2         Arkansas     Little Rock       2,967,392         +293,992
3          Arizona         Phoenix       6,730,413       +1,599,781
4       California      Sacramento      38,596,972       +4,725,324
5         Colorado          Denver       5,350,101       +1,048,840
6      Connecticut        Hartford       3,594,524         +188,959
7         Delaware           Dover         932,487         +148,887
8          Florida     Tallahassee      19,845,911       +3,863,533
9          Georgia         Atlanta      10,067,278       +1,880,825
10          Hawaii        Honolulu       1,414,538         +203,001
11           Idaho           Boise       1,631,112         +337,159
12        Illinois     Springfield      12,884,493         +465,200
13         Indiana    Indianapolis       6,593,644         +513,159
14            Iowa      Des Moines       3,109,350         +183,026
15          Kansas          Topeka       2,900,475         +212,057
16        Kentucky       Frankfort       4,414,349         +372,580
17       Louisiana     Baton Rouge       4,644,013         +175,037
18           Maine         Augusta       1,330,513          +55,590
19        Maryland       Annapolis       5,957,283         +660,797
20   Massachusetts          Boston       6,762,596         +413,499
21        Michigan         Lansing       9,929,848           -8,596
22       Minnesota      Saint Paul       5,451,079         +531,600
23     Mississippi         Jackson       2,990,468         +145,810
24        Missouri  Jefferson City       6,056,202         +460,991
25         Montana          Helena       1,021,869         +119,674
26        Nebraska         Lincoln       1,879,321         +168,058
27          Nevada     Carson City       2,817,628         +819,371
28   New Hampshire         Concord       1,333,341          +97,555
29      New Jersey         Trenton       8,864,525         +450,175
30      New Mexico        Santa Fe       2,089,568         +270,522
31        New York          Albany      19,651,049         +674,592
32  North Carolina         Raleigh       9,932,887       +1,883,574
33    North Dakota        Bismarck         737,401          +95,201
34            Ohio        Columbus      11,602,700         +249,560
35        Oklahoma   Oklahoma City       3,878,187         +427,533
36          Oregon           Salem       3,963,244         +541,845
37    Pennsylvania      Harrisburg      12,788,313         +507,259
38    Rhode Island      Providence       1,055,936           +7,617
39  South Carolina        Columbia       4,823,617         +811,605
40    South Dakota          Pierre         849,129          +94,285
41       Tennessee       Nashville       6,541,223         +851,940
42           Texas          Austin      26,964,333       +6,112,513
43            Utah  Salt Lake City       2,936,879         +703,710
44         Vermont      Montpelier         625,214          +16,387
45        Virginia        Richmond       8,310,993       +1,232,478
46      Washington         Olympia       7,054,655       +1,160,534
47   West Virginia      Charleston       1,849,489          +41,145
48       Wisconsin         Madison       5,751,525         +387,850
49         Wyoming        Cheyenne         582,531          +88,749

   Births 2000-2019 Deaths 2000-2019 Internal migration 2000-2019  \
0         1,109,759          901,006                      +85,710
1           199,506           68,497                       -9,032
2           712,847          543,348                      +76,445
3         1,659,007          906,630                     +714,354
4         9,587,847        4,546,217                   -1,509,708
5         1,246,323          600,563                     +212,822
6           721,822          550,078                      -96,328
7           208,081          144,858                      +46,524
8         4,071,385        3,325,544                   +1,182,974
9         2,505,267        1,337,153                     +567,135
10          338,098          185,928                      -33,108
11          420,520          213,239                     +112,341
12        3,120,026        1,936,668                     -632,866
13        1,577,157        1,078,767                      -21,734
14          720,043          523,752                      -52,205
15          725,765          463,795                      -69,962
16        1,029,544          789,090                      +82,517
17        1,170,903          785,948                     -318,811
18          244,831          243,455                      +30,725
19        1,369,078          839,872                      -95,972
20        1,392,818        1,026,043                     -276,768
21        2,239,510        1,668,503                     -540,750
22        1,291,650          735,332                      -43,962
23          755,885          547,402                      -36,545
24        1,415,242        1,047,640                      +42,041
25          220,642          166,095                      +39,938
26          482,839          286,863                      -41,144
27          663,290          374,232                     +374,762
28          249,915          199,416                      +35,087
29        1,991,362        1,334,328                     -459,803
30          502,314          298,044                      +23,215
31        4,500,939        2,836,734                   -1,686,583
32        2,254,607        1,488,844                     +675,016
33          174,351          110,784                      -19,785
34        2,663,449        2,070,496                     -368,203
35          962,384          685,198                      +39,463
36          849,335          605,151                     +178,547
37        2,647,716        2,390,543                      -40,139
38          215,856          180,414                      -44,649
39        1,066,607          782,956                     +310,572
40          217,084          133,632                       +6,822
41        1,498,863        1,126,575                     +264,570
42        7,152,765        3,157,555                     +848,702
43          946,719          279,021                      +52,582
44          114,478           99,805                       -1,124
45        1,899,603        1,130,543                     +171,420
46        1,586,133          918,624                     +238,546
47          375,158          399,583                      +16,018
48        1,269,650          893,981                      -10,443
49          133,631           81,603                      +22,382

   International migration 2000-2019 2019 housing units  \
0                           +160,631          2,284,922
1                            +87,461            319,867
2                           +126,346          1,389,159
3                           +702,674          3,076,048
4                         +5,001,325         14,367,012
5                           +517,415          2,464,109
6                           +304,167          1,524,959
7                            +55,878            443,764
8                         +2,224,554          9,674,053
9                           +954,475          4,378,350
10                          +165,524            550,328
11                          +127,567            751,113
12                        +1,109,069          5,388,210
13                          +392,779          2,921,115
14                          +174,061          1,418,600
15                          +220,581          1,288,430
16                          +186,880          2,006,335
17                          +249,763          2,089,824
18                            +8,857            750,964
19                          +626,230          2,470,307
20                          +752,989          2,928,818
21                          +538,953          4,629,605
22                          +471,290          2,477,515
23                          +105,188          1,339,047
24                          +274,505          2,819,334
25                           +32,762            519,938
26                          +160,858            851,167
27                          +254,048          1,285,681
28                           +52,594            642,298
29                          +981,104          3,641,854
30                          +148,611            948,470
31                        +2,295,913          8,404,205
32                          +686,071          4,748,148
33                           +57,799            379,974
34                          +494,879          5,232,943
35                          +230,736          1,749,520
36                          +248,300          1,808,482
37                          +540,935          5,732,580
38                           +76,599            470,177
39                          +218,918          2,351,364
40                           +63,296            401,749
41                          +313,847          3,028,437
42                        +3,622,926         11,283,892
43                          +426,479          1,133,543
44                           +14,555            339,412
45                          +809,082          3,562,258
46                          +756,428          3,195,098
47                           -11,682            894,983
48                          +280,257          2,725,153
49                           +31,321            280,281

   Housing units change from 2000             Land area  \
0                        +314,871   50,744 square miles
1                         +58,337  571,951 square miles
2                        +212,364   52,068 square miles
3                        +872,218  113,635 square miles
4                      +2,121,752  155,959 square miles
5                        +642,571  103,718 square miles
6                        +137,334    4,845 square miles
7                         +99,487    1,954 square miles
8                      +2,333,807   53,927 square miles
9                      +1,072,425   57,906 square miles
10                        +88,643    6,423 square miles
11                       +220,565   82,747 square miles
12                       +490,984   55,584 square miles
13                       +378,800   35,867 square miles
14                       +183,995   55,869 square miles
15                       +153,882   81,815 square miles
16                       +248,822   39,728 square miles
17                       +239,187   43,562 square miles
18                        +97,602   30,862 square miles
19                       +318,831    9,774 square miles
20                       +303,747    7,840 square miles
21                       +382,889   56,804 square miles
22                       +403,652   79,610 square miles
23                       +172,477   46,907 square miles
24                       +369,696   68,886 square miles
25                       +106,658  145,552 square miles
26                       +126,299   76,872 square miles
27                       +450,388  109,826 square miles
28                        +93,711    8,968 square miles
29                       +324,460    7,417 square miles
30                       +165,108  121,356 square miles
31                       +715,541   47,214 square miles
32                     +1,207,695   48,711 square miles
33                        +89,735   68,976 square miles
34                       +437,599   40,948 square miles
35                       +231,419   68,667 square miles
36                       +351,095   95,997 square miles
37                       +474,695   44,817 square miles
38                        +29,926    1,045 square miles
39                       +588,546   30,109 square miles
40                        +77,449   75,885 square miles
41                       +578,868   41,217 square miles
42                     +3,082,178  261,797 square miles
43                       +360,787   82,144 square miles
44                        +44,438    9,250 square miles
45                       +645,849   39,594 square miles
46                       +734,647   66,544 square miles
47                        +48,716   24,078 square miles
48                       +396,801   54,310 square miles
49                        +56,017   97,100 square miles

             State nickname
0            Heart of Dixie
1                Great Land
2             Natural State
3        Grand Canyon State
4              Golden State
5          Centennial State
6        Constitution State
7               First State
8            Sunshine State
9               Peach State
10              Aloha State
11                Gem State
12          Land of Lincoln
13            Hoosier State
14            Hawkeye State
15          Sunflower State
16          Bluegrass State
17            Pelican State
18          Pine Tree State
19           Old Line State
20                Bay State
21        Great Lakes State
22         North Star State
23           Magnolia State
24            Show Me State
25           Treasure State
26         Cornhusker State
27             Silver State
28            Granite State
29             Garden State
30  The Land of Enchantment
31             Empire State
32           Tar Heel State
33        Flickertail State
34            Buckeye State
35             Sooner State
36             Beaver State
37           Keystone State
38              Ocean State
39           Palmetto State
40     Mount Rushmore State
41          Volunteer State
42          Lone Star State
43            Beehive State
44     Green Mountain State
45             Old Dominion
46          Evergreen State
47           Mountain State
48             Badger State
49           Equality State

In [61]:
print(len(df.columns))

12

## Saving in csv format

In [62]:
# Save the DataFrame to a CSV file
df.to_csv('states_data.csv', index=False)

## Saving in excel format

In [64]:
df.to_excel('states_data.xlsx', index=False)

## Saving in JSON format

In [ ]:
df.to_json('data.json', orient='records', lines=True)